service: wozitech-contact-form

custom:
  environment: ${opt:stage, 'development'}
  region: ${opt:region, 'eu-west-1'}
  WOZITECH_EMAIL_ADDRESS:
    dev: warren.ayling@wozitech-ltd.co.uk
    staging: warren.ayling@wozitech-ltd.co.uk
    preprod: warren.ayling@wozitech-ltd.co.uk
    prod: warren.ayling@wozitech-ltd.co.uk

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-admin
  region: ${self:custom.region}
  endpointType: REGIONAL
  stage: ${opt:stage, 'development'}
  timeout: 5
  memorySize: 128
  environment:
    LOG_LEVEL: 0      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
  role: "arn:aws:iam::#{AWS::AccountId}:role/${self:provider.stage}-lambda"

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - '**/*'
    - .git/**

functions:
  sendEmailToWoziTech:
    handler: contactForm.handler
    role: "arn:aws:iam::924132851837:role/lambda_and_ses"
    environment:
      EMAIL_ADDRESS: "${self:custom.WOZITECH_EMAIL_ADDRESS.${self:provider.stage}}"
    tags:
      owner: "WOZiTech"
      application: "Contact Form Send Email"
    package:
      include:
        - contactForm.js
plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-include-dependencies